name: Prepare .env File

on:
  push:
    branches:
      - main

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

    - name: Upload .env file
      uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: .env
